org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.problems.report=false

github_org=crystal-development-llc
github_name=FastAsyncWorldEdit-Legacy
description=FastAsyncWorldEdit for legacy Minecraft supporting modern Java.
group=co.crystaldev.fawe
version=22.1286.1-SNAPSHOT